name: .NET Core Action
on:  push      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: dotnet Publish
        run: dotnet publish -c Release --framework netcoreapp3.1
        # make an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: ${{ github.workspace }}/*/bin/Release/netcoreapp3.1/publish/